Add component "rust-src" manually during step 3
In default rust install on Windows, rust-src is not set up.

When building a contract (e.g. Flipper), the following error is thrown:
```
ERROR: Building with xbuild

Caused by:
    `rust-src` component not found. Run `rustup component add rust-src`.
```

However, following this command will not add it to nightly - need to specify it manually.